window.GAME_CONFIG = {
  baseMaxHp: 200,
  nestMaxHp: 50,
  creatureDamage: 1,
  playerCreatureMaxHp: 3,
  enemyCreatureMaxHp: 1,
  creatureSpeed: 80,
  creatureRadius: 9,
  creatureAttackRangePadding: 4,
  buildingAttackRangePadding: 0,
  buildingCollisionPadding: 0,
  deathDelayMs: 200,
  playerBaseWidth: 92,
  playerBaseHeight: 92,
  enemyBaseWidth: 170,
  enemyBaseHeight: 90,
  nestWidth: 96,
  nestHeight: 64,
  attackWindup: 0.1,
  attackCooldown: 0.8,
  creatureSpacing: 6,
  opponentSpacing: 0,
  separationStrength: 0.5,
  creaturesCanFight: true,
  spawnIntervalMs: 3000,
};
